apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: metricbeat-hosts
  namespace: test-elasticsearch
spec:
  config:
    metricbeat:
      modules:
        - host: localhost
          metricsets:
            - remote_write
          module: prometheus
          port: 9201
  deployment:
    podTemplate:
      metadata:
        creationTimestamp: null
      spec:
        containers:
          - name: metricbeat
            ports:
              - containerPort: 9201
            securityContext:
              privileged: true
              runAsUser: 0
        serviceAccountName: metricbeat
    replicas: 1
    strategy: {}
  elasticsearchRef:
    name: elasticsearch-sample
  kibanaRef:
    name: kibana-sample
  type: metricbeat
  version: 8.2.0
