apiVersion: v1
kind: ConfigMap
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
data:
  config.yaml: |
    prometheus:
      remoteWrite:
         - url: http://thanos-receive.monitoring.svc.cluster.local:19291/api/v1/receive
           tlsConfig:
             insecure_skip_verify: yes
           writeRelabelConfigs:
            - sourceLabels: [__name__, namespace]
              action: keep
              regex: "myapp_client_connected;prometheus-test"
