apiVersion: v1
kind: Service
metadata:
  name: avalanche
  namespace: prom-test
spec:
  ports:
  - name: http
    port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    name: avalanche
  type: ClusterIP
